### ISSUE TITLE
Relational `KSTest` crashes with `IncomputableMetricError` if a table doesn't have numerical columns

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDMetrics#109]
### Environment Details

* SDMetrics version: 0.4.1
* Python version: 3.7

### Error Description

The relational `KSTest` is supposed to run the `KSTest` on all numerical columns in all tables and return the average score.

However, this test crashes if it encounters a table that has no numerical columns. I expect this test to succeed as long as there is at least 1 numerical column in any of the tables.

### Steps to reproduce

Use the relational demo dataset and pass it in with the metadata.

```python
from sdv.metrics.demos import load_multi_table_demo
from sdv.metrics.relational import KSTest

real_data, synthetic_data, metadata = load_multi_table_demo()
KSTest.compute(real_data, synthetic_data, metadata)
```

Output:
```
/usr/local/lib/python3.7/dist-packages/sdmetrics/single_table/base.py in _select_fields(cls, metadata, types)
     78 
     79         if len(fields) == 0:
---> 80             raise IncomputableMetricError(f'Cannot find fields of types {types}')
     81 
     82         return fields

IncomputableMetricError: Cannot find fields of types ('numerical',)
```

I believe this is happening because table `sessions` has no numerical columns. Interestingly, it _does_ work if I exclude the `metadata` object -- because then it starts assuming that the `id` field is a numerical column.

```python
KSTest.compute(real_data, synthetic_data)

0.8555555555555556
```

**Comment by katxiao** [comment]
Hi @npatki. We updated the metric behavior so that it crashes if there are no numerical columns, because in that scenario we have no way of computing the metric. Before, it would return `nan`. 

I believe this is expected behavior. With the latest release, we have chosen to raise an explicit error instead of failing silently.

**Comment by npatki** [comment]
@katxiao You can still compute the metic because the other tables have numerical columns. 

Metadata details:

- Table `sessions` has no numerical columns
- Table `transactions` has a numerical column (`amount`)
- Table `users` has a numerical column (`age`)

This metric is crashing because `sessions` has no numerical columns. But I think it should actually be computing `KSTest` on `amount` and `age` and returning that average.
