### ISSUE TITLE
README doesn't accurately describe the output of `compute_metrics`

### ISSUE THREAD

**Issue by fealho** [sdv-dev/SDMetrics#126]
The current `README` doesn't print the latest output. More specifically, the command `sdmetrics.compute_metrics(metrics, real_data, synthetic_data, metadata=metadata)` currently doesn't print the same as what the README prints (e.g. the current code produces a column named `error` containing `None` values which the README doesn't have, as well as other changes).

**Comment by npatki** [comment]
In addition to the `error` column, the newer version of SDMetrics will also include new metrics & changes to the names of the existing metrics.

**Comment by npatki** [comment]
Marking this as stale, as we've changed the README to include the newer reports functionality and their output.
