### ISSUE TITLE
BNLikelihood not properly listed as a single table metric

### ISSUE THREAD

**Issue by haaksb** [sdv-dev/SDMetrics#148]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDMetrics version: 0.5.0
* Python version: 3.9
* Operating System: Windows

### Error Description

I want to go through a number of tests using single table metrics, but Bayesian Networks(BNLikelihood do not work using the method below, where metric is a list of tests I want to do:

tests=SingleTableMetric.get_subclasses()
out=tests[metric].compute(real_df, synth_df, metadata=config)

To add to this, in the readme here(https://github.com/sdv-dev/SDMetrics/tree/master/sdmetrics/single_table), BNLikelihood is not listed as output of SingleTableMetric.get_subclasses(), though it is mentioned in the readme as a test.

I do realise I can use BNLikelihood.compute() instead, so this probably isnt high priority, but I thought I should mention it.

### Steps to reproduce

See above

I dont have the time to reproduce the error right now, but the error message was a typical "this key does not exist" type of thing.

**Comment by npatki** [comment]
Thanks for filing @haaksb. Confirming that `BNLikelihood` is not appearing (although `BNLogLikelihood` is).

Let's keep this open for tracking.
