### ISSUE TITLE
Improve usability & documentation: Make SDMetrics easily interpretable

### ISSUE THREAD

**Issue by abhisheknagar1983** [sdv-dev/SDMetrics#15]
* SDMetrics version: 0.4.5
* Python version: 3.6.9
* Operating System: Linux RHEL

### Description

As a end user we are finding it difficult to interpret the result of SDMetrics. The documentation for SD matrices could be more elaborated, so that user can interpret the quality of data generated easily. There are some parameter as in the report which are hard to guess -
1) Overall score.
2) Detectability of synthetic data.

More compressive documentation is needed for SDMetrics.
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment]
Hi @abhisheknagar1983, we are actively working on improving the usability of SDMetrics. Hopefully within the next few releases, we'll have incorporated new features & better documentation.

**Comment by Grayangelz** [comment]
850393700787

**Comment by npatki** [comment]
Hi all, I'm closing off this older issue. You can view the updated SDMetrics documentation at: https://docs.sdv.dev/sdmetrics/

Let us know if you have any issues!
