### ISSUE TITLE
reports.generate 'fields' index issue

### ISSUE THREAD

**Issue by bdeck8317** [sdv-dev/SDMetrics#239]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDMetrics version: '0.7.0'
* Python version:  3.9.13
* Operating System: Windows under WSL2--Unbuntu

### Error Description

Attepmting to generate report from the following command ```report = QualityReport()
    report.generate(x_y_df, synth_data, meta_data)```

### Steps to reproduce

```
x_y_df.to_json(reports_path + '/' + 'xy_df.json')

    with open(reports_path + '/' + 'xy_df.json') as f:
        meta_data = json.load(f)

    
    # Initialize report
    report = QualityReport()
    report.generate(x_y_df, synth_data, meta_data)
```

Traceback: 
```
File "/home/bdeck8317/miniconda3/lib/python3.9/site-packages/sdmetrics/reports/single_table/quality_report.py", line 72, in generate
    self._metric_results[metric.__name__] = metric.compute_breakdown(
  File "/home/bdeck8317/miniconda3/lib/python3.9/site-packages/sdmetrics/single_table/multi_single_column.py", line 147, in compute_breakdown
    return cls._compute(
  File "/home/bdeck8317/miniconda3/lib/python3.9/site-packages/sdmetrics/single_table/multi_single_column.py", line 68, in _compute
    real_data, synthetic_data, metadata = self._validate_inputs(
  File "/home/bdeck8317/miniconda3/lib/python3.9/site-packages/sdmetrics/single_table/base.py", line 119, in _validate_inputs
    fields = metadata['fields']
KeyError: 'fields'

```

Thanks,
Ben

**Comment by npatki** [comment]
Hi @bdeck8317, thanks for filing this issue.

From looking at your code, I'm confused by the following lines:

```python
x_y_df.to_json(reports_path + '/' + 'xy_df.json')

with open(reports_path + '/' + 'xy_df.json') as f:
    meta_data = json.load(f)
```

Is `x_y_df` your data? It seems like you are converting the data itself as a JSON object and then loading it in as `meta_data`.

In SDMetrics the metadata is a _description_ of the data, not the data itself. Assuming you are evaluating quality for a single table, [here is the reference](https://docs.sdv.dev/sdmetrics/getting-started/metadata/single-table-metadata) for how to write a metadata dictionary. It may be helpful to go through the [Quickstart Guide](https://docs.sdv.dev/sdmetrics/getting-started/quickstart), which provides an example of how we expect the data and metadata to be formatted.

Let me know if I'm misunderstanding anything. If you can share your metadata, I'm happy to inspect it to verify that it's following the expected format.

**Comment by bdeck8317** [comment]
@npatki, yes you are correct. I will create a JSON of my data description. Thank you!

**Comment by npatki** [comment]
No problem! Feel free to reply or create new issues if you encounter any other bugs
