### ISSUE TITLE
KeyError: 'fields' , --> reports.generate 'fields' 

### ISSUE THREAD

**Issue by ketandaryanani** [sdv-dev/SDMetrics#247]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDMetrics version:'0.7.0'
* Python version: 3.8.8
* Operating System: Windows server  2016 dataserver

### Steps to reproduce

I tried to use sdmetrics to compare the Synthetic data.
Example of the data set  

<html>
<body>

Customer | State | Customer Lifetime Value | Response | Coverage | Education | Effective To Date | EmploymentStatus | Gender | Income | ... | Months Since Policy Inception | Number of Open Complaints | Number of Policies | Policy Type | Policy | Renew Offer Type | Sales Channel | Total Claim Amount | Vehicle Class | Vehicle Size
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BU79786 | Washington | 2763.519279 | No | Basic | Bachelor | 2/24/11 | Employed | F | 56274 | ... | 5 | 0 | 1 | Corporate Auto | Corporate L3 | Offer1 | Agent | 384.811147 | Two-Door Car | Medsize
QZ44356 | Arizona | 6979.535903 | No | Extended | Bachelor | 1/31/11 | Unemployed | F | 0 | ... | 42 | 0 | 8 | Personal Auto | Personal L3 | Offer3 | Agent | 1131.464935 | Four-Door Car | Medsiz

</body>
</html>

loaded the Gaussian copula pkl model to generate the synthetic data and created a metadata on the original dataset to use it in quality report.
I have pasted the Metadata created for the data above:
{'fields': {'Customer': {'type': 'id', 'subtype': 'string'},
  'State': {'type': 'categorical'},
  'Customer Lifetime Value': {'type': 'numerical', 'subtype': 'float'},
  'Response': {'type': 'categorical'},
  'Coverage': {'type': 'categorical'},
  'Education': {'type': 'categorical'},
  'Effective To Date': {'type': 'categorical'},
  'EmploymentStatus': {'type': 'categorical'},
  'Gender': {'type': 'categorical'},
  'Income': {'type': 'numerical', 'subtype': 'integer'},
  'Location Code': {'type': 'categorical'},
  'Marital Status': {'type': 'categorical'},
  'Monthly Premium Auto': {'type': 'numerical', 'subtype': 'integer'},
  'Months Since Last Claim': {'type': 'numerical', 'subtype': 'integer'},
  'Months Since Policy Inception': {'type': 'numerical', 'subtype': 'integer'},
  'Number of Open Complaints': {'type': 'numerical', 'subtype': 'integer'},
  'Number of Policies': {'type': 'numerical', 'subtype': 'integer'},
  'Policy Type': {'type': 'categorical'},
  'Policy': {'type': 'categorical'},
  'Renew Offer Type': {'type': 'categorical'},
  'Sales Channel': {'type': 'categorical'},
  'Total Claim Amount': {'type': 'numerical', 'subtype': 'float'},
  'Vehicle Class': {'type': 'categorical'},
  'Vehicle Size': {'type': 'categorical'}},
 'primary_key': 'Customer'}.-->

```
#creating metadata
metadata.add_table(
    name='INS',
    data=data2,
    primary_key='Customer'
     )


report = QualityReport()
report.generate(data2, synthetic_data,metadata)


error:
Creating report:   0%|          | 0/4 [00:00<?, ?it/s]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [54], in <cell line: 2>()
      1 report = QualityReport()
----> 2 report.generate(data2, synthetic_data,metadata)

File ~\.conda\envs\SDVENV\lib\site-packages\sdmetrics\reports\single_table\quality_report.py:72, in QualityReport.generate(self, real_data, synthetic_data, metadata)
     70 for metric in tqdm.tqdm(metrics, desc='Creating report'):
     71     try:
---> 72         self._metric_results[metric.__name__] = metric.compute_breakdown(
     73             real_data, synthetic_data, metadata)
     74     except IncomputableMetricError:
     75         # Metric is not compatible with this dataset.
     76         self._metric_results[metric.__name__] = {}

File ~\.conda\envs\SDVENV\lib\site-packages\sdmetrics\single_table\multi_single_column.py:147, in MultiSingleColumnMetric.compute_breakdown(cls, real_data, synthetic_data, metadata, **kwargs)
    123 @classmethod
    124 def compute_breakdown(cls, real_data, synthetic_data, metadata=None, **kwargs):
    125     """Compute this metric broken down by column.
    126 
    127     This is done by computing the underlying SingleColumn metric to all the
   (...)
    145             A mapping of column name to metric output.
    146     """
--> 147     return cls._compute(
    148         cls, real_data, synthetic_data, metadata, store_errors=True, **kwargs)

File ~\.conda\envs\SDVENV\lib\site-packages\sdmetrics\single_table\multi_single_column.py:68, in MultiSingleColumnMetric._compute(self, real_data, synthetic_data, metadata, store_errors, **kwargs)
     43 def _compute(self, real_data, synthetic_data, metadata=None, store_errors=False, **kwargs):
     44     """Compute this metric for all columns.
     45 
     46     This is done by computing the underlying SingleColumn metric to all the
   (...)
     66             A mapping of column name to metric output.
     67     """
---> 68     real_data, synthetic_data, metadata = self._validate_inputs(
     69         real_data, synthetic_data, metadata)
     71     fields = self._select_fields(metadata, self.field_types)
     72     invalid_cols = set(metadata['fields'].keys()) - set(fields)

File ~\.conda\envs\SDVENV\lib\site-packages\sdmetrics\single_table\base.py:119, in SingleTableMetric._validate_inputs(cls, real_data, synthetic_data, metadata)
    116 if not isinstance(metadata, dict):
    117     metadata = metadata.to_dict()
--> 119 fields = metadata['fields']
    120 for column in real_data.columns:
    121     if column not in fields:

KeyError: 'fields'

```

**Comment by npatki** [comment]
Hi @ketandaryanani, nice to meet you!

The `metadata` that you pass in should be a **Python dictionary** not any other type of object. Please use the `to_dict()` method to render it as a dictionary. For more info, view the detailed documentation for SDMetrics Quality report [here](https://docs.sdv.dev/sdmetrics/reports/quality-report/single-table-quality-report#generating-the-report).

PS. The `add_table` method you are using is not guaranteed to correctly identify all the column types. I would recommend writing the metadata as a dictionary yourself to make sure it is accurate. See the SDMetrics metadata guide [here](https://docs.sdv.dev/sdmetrics/getting-started/metadata/single-table-metadata).

**Comment by ketandaryanani** [comment]
Hello @npatki ,
Thank you  , I had followed the to_dict(), which didnt work.
On careful analysis, I understood the difference , my metadata was following pattern of a multi-table metadata.
When I removed table name and corrected few dictionaries, and rendered it as dictionary,  it worked well for me.
New metadata:
{ "primary_key": "Customer",
"fields": {"Customer": {"type": "id", "subtype": "string"}, 
"State": {"type": "categorical","pii": "True"}, 
"Customer_Lifetime_Value": {"type": "numerical", "subtype": "float"}, 
"Response": {"type": "boolean"},
 "Coverage": {"type": "categorical"}, 
"Education": {"type": "categorical"},
 "Effective_To_Date": {"type": "categorical", "format": "%m/%d/%Y"}, 
"EmploymentStatus": {"type": "categorical"}, 
"Gender": {"type": "categorical"}, 
"Income": {"type": "numerical", "subtype": "integer"}, 
"Location_Code": {"type": "categorical"}, 
"Marital_Status": {"type": "categorical"}, 
"Monthly_Premium_Auto": {"type": "numerical", "subtype": "integer"}, 
.
.
.
}}} 

Thank you again.
