### ISSUE TITLE
Accademic Paper to cite?

### ISSUE THREAD

**Issue by andreagalloni92** [sdv-dev/SDMetrics#249]
Is there any paper to cite related to this library? I am evaluating some synthetic data for a publication so I wanted to include your contribution among the citations. 

Thanks 
Andrea Galloni

**Comment by npatki** [comment]
Hi @andreagalloni92, great to hear!

While there isn't yet an associated paper, you can currently cite the [SDMetrics documentation](https://docs.sdv.dev/sdmetrics/) as a manual if that works.

Using [BibTeX](https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management#BibTeX):

```latex
\usepackage{hyperref}

@manual{
    sdmetrics,
    title = {Synthetic Data Metrics},
    organization = {DataCebo, Inc.},
    year = {2022},
    month = {9},
    note = {v0.7.0},
    url = {https://docs.sdv.dev/sdmetrics/}
}
```

**Comment by npatki** [comment]
Hi @andreagalloni92, I'm closing off this issue since we've answered your question.

Feel free to reply if there is anything more to discuss, and I will reopen the issue.
