### ISSUE TITLE
"Column Shapes" and "Column Pair Trends" Calculation Inconsistency

### ISSUE THREAD

**Issue by gabriel-berardi** [sdv-dev/SDMetrics#254]
### Environment Details

* SDMetrics version: 0.8.0
* Python version: 3.7.15
* Operating System: Linux Mint 20.3 Cinnamon

### Error Description

The bug relates to the `QualityReport()`. The result of `report.get_properties()` does not match a manual calculation through `get_details()`.

More specifically, the `Column Shapes` and `Column Pair Trends` from `report.get_properties()` do not match the calculation through `report.get_details('Column Shapes')['Quality Score'].mean()` and/or `report.get_details('Column Pair Values')['Quality Score'].mean()`.

### Steps to reproduce

The error ocurred for both `Column Shapes` and `Column Pair Trends` on my own dataset. I reproduced the error with SDV's `student_placements` dummy dataset, as follows:

```
data = load_tabular_demo('student_placements')
data = data[['gender', 'salary', 'placed']]
model = GaussianCopula()
model.fit(data)
new_data = model.sample(num_rows=200)
metadata = {
    "fields": {
        "gender": {
            "type": "categorical"
        },
        "salary": {
            "type": "numerical", 
            "subtype": "float"
        },
        "placed": {
            "type": "categorical"
        }
    }
}
report = QualityReport()
report.generate(data, new_data, metadata)
```

> Creating report: 100%|██████████| 4/4 [00:00<00:00, 46.59it/s]
> Overall Quality Score: 83.37%
> 
> Properties:
> Column Shapes: 84.75%
> Column Pair Trends: 81.98%

```
report.get_properties()
```
> 
> Column Shapes: 0.847540
> Column Pair Trends: 0.819845

```
print(report.get_details('Column Shapes')['Quality Score'].mean())
print(report.get_details('Column Pair Trends')['Quality Score'].mean())
```
> 0.8725462671974299
> 0.8198449612403099

The unexpected behaviour here is that 0.847540 ≠ 0.8725462671974299. In the dummy dataset, the error only occurs for `Column Shapes` while `Column Pair Trends` is correct. In my own dataset, both numbers do not match.

**Comment by npatki** [comment]
Hi @gabriel-berardi, thanks for filing this bug. I can replicate it on my end. 

We'll take a look and update it when we find the root cause. For now, I would suggest using:

```python
print(report.get_details('Column Shapes')['Quality Score'].mean())
print(report.get_details('Column Pair Trends')['Quality Score'].mean())
```

As this is the intended usage.
