### ISSUE TITLE
NewRowSynthesis should ignore PrimaryKey column

### ISSUE THREAD

**Issue by yoid2000** [sdv-dev/SDMetrics#260]
### Problem Description

It appears that the `NewRowSynthesis` measure includes the `primary_key` column in its analysis. I can feed it two tables that are identical except for the `primary_key` column, and it will measure every synthetic data row as new even though practically speaking none of them are new.

### Expected behavior

Ignore the `primary_key` column when doing `NewRowSynthesis`.

**Comment by npatki** [comment]
Thanks for filing this issue @yoid2000.

I can replicate the current behavior you're describing and I also agree that `primary_key` should not be included in the computation of this metric. We'll keep this issue open for tracking progress.

While we're at it, we should also make sure that other column types are not being used in the `NewRowSynthesis` computation including:
- Other types of keys (eg. foreign keys)
- PII data
