### ISSUE TITLE
README.md example has a bug 

### ISSUE THREAD

**Issue by Pverheijen** [sdv-dev/SDMetrics#262]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDMetrics version: 0.7.0
* Python version: 3.8
* Operating System: Linux VM
* pandas version: 1.2.4

### Error Description

Following the README.md example of calculating the BoundaryAdherence:

Running the code gives the following error: 
AttributeError: 'Series' object has no attribute 'columns'

I would expect the code to generate the BoundaryAdherence for the start_date column of the real_data pandas dataframe and synthetic_Data pandas dataframe

### Steps to reproduce

Follow this snippet from the README.md that shows the usage of BoundaryAdherence

```python 
# calculate whether the synthetic data respects the min/max bounds
# set by the real data
from sdmetrics.single_table import BoundaryAdherence

BoundaryAdherence.compute(
    real_data['start_date'],
    synthetic_data['start_date']
)
```

### Solution
I will open a PR for this later today or tomorrow. 

```python
type(real_data['start_date']) 
``` 
Returns a pandas.core.series.Series

```python
type(real_data[['start_date']])
``` 
Returns a pandas.core.frame.DataFrame

BoundaryAdherence.compute() expects DataFrames for both the real_data and synthetic_data arguments. 

```python
# calculate whether the synthetic data respects the min/max bounds
# set by the real data
from sdmetrics.single_table import BoundaryAdherence

BoundaryAdherence.compute(
    real_data[['start_date']],
    synthetic_data[['start_date']]
)
```

**Comment by Pverheijen** [comment]
Opened a PR: https://github.com/sdv-dev/SDMetrics/pull/263

**Comment by npatki** [comment]
Hi @Pverheijen, the fix is to change `single_table` (in line 3) to **`single_column`**. Let me know if that doesn't work.

**Comment by Pverheijen** [comment]
That seems to work, I'll update the PR
