### ISSUE TITLE
Fix `'duration'` column in the single table demo

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDMetrics#266]
### Problem Description

The `'duration'` column in the single table demo is being represented as a pandas `object` dtype and specified as `'categorical'` in the metadata. However, this column actually represents numerical data. 

### Expected behavior

Update some of the returned values in the `load_demo` call for single table.

```python
from sdmetrics import load_demo 

real_data, synthetic_data, metadata = load_demo(modality='single_table')
```

1. The `metadata` dict should specify that the `'duration'` column is `'numerical'`.
```python
'duration': {'type': 'numerical', 'subtype': 'integer'},
```

2. The returned DataFrames (`real_data` and `synthetic_data`) should make sure that `duration` is represented as a number, not a `object`.

**Comment by amontanez24** [comment]
If I'm not mistaken, I think the data is the `duration` column is only one of 4 values (0, 3, 6, 12) or something like that. I believe that's why we wanted to treat it as categorical
