### ISSUE TITLE
Noblemen - Kolmogorov–Smirnov 

### ISSUE THREAD

**Issue by akashmukherjee1985** [sdv-dev/SDMetrics#278]
Hello Team,

First of all many thanks for creating such a wonderful package. I tried the model method and it helps.

I read how the model evaluates base data and over-sampled data' overall score. It's interesting.
So, I read about KS Complement. Here, 'KS' denotes the name Kolmogorov–Smirnov test statistics.

Just had an observation - on the Nobleman's name over your website. Snapshots attached.  

Correct name can be found in wiki:
https://en.wikipedia.org/wiki/Kolmogorov%E2%80%93Smirnov_test

So, if it is the same 'Kolmogorov', you would like to edit it. Or, please let me know if I missed anything.
Thanks again for helping! Happy journey.

Best,
friend

![kol2](https://user-images.githubusercontent.com/75519415/204792261-a1ce0d60-a278-4c45-9e41-0b75f2c987fd.png)
![kol](https://user-images.githubusercontent.com/75519415/204792288-2b31b18d-860e-4801-b9da-ec24ffd05c11.png)

**Comment by npatki** [comment]
Hi @akashmukherjee1985, thanks for catching this. The page should be updated now if you refresh the URL.

Here:
<img width="822" alt="image" src="https://user-images.githubusercontent.com/3227804/204832932-513ec542-392c-4363-b0a4-e69ade7ef66e.png">

And here:
<img width="873" alt="image" src="https://user-images.githubusercontent.com/3227804/204832995-4609225e-033f-4f18-b24e-85243457af02.png">

I'm marking this as resolved. Please feel free to reply if there's any spots I missed!
