### ISSUE TITLE
Transformer should not be fit on test data

### ISSUE THREAD

**Issue by dionman** [sdv-dev/SDMetrics#291]
### Environment Details

* SDMetrics version: v0.8.1 
* Python version: 3.9
* Operating System: Ubuntu

### Error Description

At current implementation of MLEfficacyMetric base class, the transformer is fit on the test data
https://github.com/sdv-dev/SDMetrics/blob/6983bc075073a794aabb4a9d48badfbbf0f6ec70/sdmetrics/single_table/efficacy/base.py#L50 This undesirably leaks information from the (unseen) test dataset, biasing the reported metrics. Instead `fit_transform` should be applied on the train data and `transform` on the test data.

**Comment by npatki** [comment]
Thanks for filing this @dionman. I'll check back in with the team in case there's any reason why it was implemented the way it is. Will keep this issue open to report any progress or updates.

**Comment by dionman** [comment]
thanks - are there any updates on this?

**Comment by npatki** [comment]
Hi @dionman, this bug has been added to our queue. We'll use this issue to provide any updates.
