### ISSUE TITLE
Sometimes graphs don't show when using Jupyter notebook

### ISSUE THREAD

**Issue by amontanez24** [sdv-dev/SDMetrics#322]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDMetrics version: 0.9.2
* Python version: 3.9
* Operating System: MacOs

### Error Description

When running `get_visualization` in jupyter notebook, the graph doesn't show up. Sometimes restarting the kernel, clearing the output and rerunning helps.

### Steps to reproduce

```python
quality_report = QualityReport()
quality_report.generate(
    input_data,
    output_data,
    metadata
)
quality_report.get_visualization('Column Shapes', table_name='agents')
```

**Comment by awsxcrd** [comment]
Hi, have you solved the problem? I have the same bug on windows, can you give me some suggestions?

**Comment by npatki** [comment]
Hi @amontanez24 and @awsxcrd I was able to replicate this problem. 

**Workaround**: The plots are showing pretty consistently if I add the following lines to the top of my notebook:

```python
from plotly.offline import init_notebook_mode

init_notebook_mode(connected=True)
```

Let me know if that resolves the issue for you. If so, we can think about making this more seamless inside of SDMetrics itself.

**More context**: We use Plotly as our graphing library for SDMetrics. Some searches on the Plotly community forum led me to [this conversation](https://community.plotly.com/t/unable-to-see-plot-in-jupyter-notebook/29317/3).

**Comment by amontanez24** [comment]
Writing 
```python
import plotly.io as pio
pio.renderers.default='iframe'
```
before running any visualization commands seemed to work for me
