### ISSUE TITLE
Is there a reason this package doesn't support Python 3.11?

### ISSUE THREAD

**Issue by HarrisonWilde** [sdv-dev/SDMetrics#346]
### Problem Description

See the title? Just curious as its the only dep in our project not supporting 3.11 which would be nice for some of its benefits.

**Comment by npatki** [comment]
Hi @HarrisonWilde, thanks for bringing this to our attention.

I believe the issue used to be with `torch` not working on certain platforms in Python 3.11. However now that torch 2.0 is out, we should be able to upgrade torch first and then allow Python 3.11.

**Comment by HarrisonWilde** [comment]
That's great news, thanks Neha, any idea of a timeline?

**Comment by npatki** [comment]
Hi @HarrisonWilde I do not have a specific date, but this is in the queue. 

Duping this against #353, which we'll use to track it. Thanks!
