### ISSUE TITLE
Figures are not shown on VSCode

### ISSUE THREAD

**Issue by R-Palazzo** [sdv-dev/SDMetrics#528]
### Environment Details
* SDMetrics version: main
* Python version: 3.8
### Error Description

When I run:
```
from sdmetrics.demos import load_demo
from sdmetrics.reports.single_table import QualityReport

real_data, synthetic_data, metadata = load_demo(modality='single_table')
report = QualityReport()

report.generate(real_data, synthetic_data, metadata)
fig = report.get_visualization('Column Shapes')
fig.show()
```
On my notebook on vscode, I can't see the figure.
### Workaround
Doing:
`fig.show(renderers='vscode')` instead of `fig.show()` should work.

Modifying this line:
https://github.com/sdv-dev/SDMetrics/blob/004fbbe59a4abca3de920ffee96f451a907f7186/sdmetrics/visualization.py#L34
To this:
`pio.renderers.default = 'vscode+iframe'`

fixes the issue on vscode

**Comment by srinify** [comment]
I was looking through our older issues around plots not rendering in VSCode Jupyter experience and starting close them out. The issue isn't related to any of the SDV libraries and requires just a single line code (which @R-Palazzo rightly points out involves just changing the renderer for plotly).

https://github.com/sdv-dev/SDV/issues/1734#issuecomment-2027740751
