### ISSUE TITLE
Improve metric subclasses organization

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDMetrics#54]
The current class organization includes some metrics which are usable on their own, like `BNLikelhood`, which have subclasses and therefore are not picked by the `get_subclasses` method. As a result of this, `BNLikelihood` is not available in the `sdv.evaluation.evaluate` function: https://github.com/sdv-dev/SDV/issues/327

The class organization and subclass selection should be reviewed to ensure that all the usable metrics are properly selected by the `get_subclasses` method.

**Comment by npatki** [comment]
I'm marking this as `obsolete` since we:

- No longer have an `sdv.evaluation.evaluate` module (we integrate with reports instead)
- Will be slowly updating to a newer organization that accounts for the multi-level metrics hierarchy within a single file
