### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by iamamiramine** [sdv-dev/SDMetrics#612]
https://github.com/sdv-dev/SDMetrics/blob/c991419bd27fc5052ed46934a86c5ea644abd950/sdmetrics/single_table/privacy/util.py#L125

I am getting a KeyError when running Privacy evaluation metrics. The referenced line of code is the source of the issue

**Comment by iamamiramine** [comment]
Fixed it by using iloc. Can you please confirm?
```
for i in df_copy:
        column = df_copy[i]
        for j in range(len(column)):
            entry = column.iloc[j]  # instead of df_copy[i][j]
```

**Comment by srinify** [comment]
Hi there @iamamiramine 

I ran the privacy metrics in sdmetrics on a sample dataset and wasn't able to reproduce the issue. Do you mind sharing more information about:

- the version of SDMetrics you're using
- the code you ran
- metadata visualization for your real & synthetic data (`metadata.visualize()` would be super helpful)

**Comment by srinify** [comment]
Hi there @iamamiramine I haven't heard from you so I'm going to close this issue out for now! If you're still running into it, feel free to open a new issue with some more information about:

- the version of SDMetrics you're using
- the code you ran
- metadata visualization for your real & synthetic data (`metadata.visualize()` would be super helpful)
