### ISSUE TITLE
Update docs TableStructure metric

### ISSUE THREAD

**Issue by R-Palazzo** [sdv-dev/SDMetrics#641]
### Expected behavior

Now that SDMetrics-0.16.0 has been released with the updated computation for the TableStructure metric, we can update the docs of this [page](https://docs.sdv.dev/sdmetrics/metrics/metrics-glossary/tablestructure).

**Comment by npatki** [comment]
For future reference: The reason why we need to update the docs for SDMetrics 0.16.0 is due to https://github.com/sdv-dev/SDMetrics/issues/631

**Comment by npatki** [comment]
This has now been merged.
