### ISSUE TITLE
Upgrade dependency ranges

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDMetrics#69]
The latest versions of the libraries `pandas`, `sktime` and `pomegranate` are not supported by `sdmetrics`:

| Library | Upper bound (unsupported) | Latest release |
|-|-|-|
| `pandas` | 1.1.5 | 1.3.1 |
| `pomegranate` | 0.14.2 | 0.14.5 |
| `sktime` | 0.6 | 0.7.0 |

We should investigate why and update the code if necessary to support them.

**Comment by katxiao** [comment]
https://github.com/sdv-dev/Copulas/issues/266 addresses `pandas`, and #81 addresses `sktime`. Since `pomegranate` is now marked as optional, I am going to close this issue. We can open another issue if we want to bump the optional pomegranate range after we stop supporting py36.
